# Global settings are optional

channels:
  - name: Certus IMU
    address: ipc:///tmp/imu.sock
    topic: ""

  - name: Encoder
    address: ipc:///tmp/encoders.sock
    topic: ""

# Time check
check_time: true

# Disks
check_disks:
  - path: /
    warning: 150 # GB
    critical: 50 # GB

